# Generated by Django 3.1.2 on 2020-10-28 02:41

from django.db import migrations, models
import mechbot.managers


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', mechbot.managers.DiscordUserOauth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
