# Generated by Django 3.1.2 on 2020-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0002_auto_20201028_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='email',
            field=models.CharField(default='test@email.com', max_length=320),
            preserve_default=False,
        ),
    ]
