# Generated by Django 3.1.2 on 2020-11-29 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0003_discorduser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_word', models.CharField(max_length=50, null=True)),
                ('tag', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=7, null=True)),
                ('hit_counter', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechbot.discorduser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
