# Generated by Django 3.1.2 on 2020-11-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_active',
            field=models.CharField(default='t', max_length=1),
        ),
    ]
