# Generated by Django 3.1.2 on 2020-11-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0006_discorduser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
