# Generated by Django 3.1.2 on 2020-11-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0007_auto_20201129_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discorduser',
            old_name='discord_tag',
            new_name='username',
        ),
    ]
