# Generated by Django 3.1.2 on 2020-11-30 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0008_auto_20201129_0540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Alert',
        ),
    ]
