# Generated by Django 3.1.2 on 2020-11-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0009_auto_20201130_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='region',
            new_name='origin',
        ),
        migrations.AlterField(
            model_name='alert',
            name='tag',
            field=models.CharField(choices=[('Selling', 'Selling'), ('Buying', 'Buying'), ('Trading', 'Trading'), ('Group Buy', 'Group Buy'), ('Vendor', 'Vendor'), ('Service', 'Service'), ('Interest Check', 'Interest Check'), ('Artisan', 'Artisan'), ('Sold', 'Sold'), ('Purchased', 'Purchased'), ('Traded', 'Traded'), ('Meta', 'Meta'), ('Giveaway', 'Giveway'), ('Fundraiser', 'Fundraiser')], max_length=20),
        ),
    ]
