# Generated by Django 3.1.2 on 2020-12-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0012_auto_20201201_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='email',
        ),
    ]
