# Generated by Django 3.1.2 on 2020-12-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0013_remove_discorduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='can_dm',
            field=models.BooleanField(default=False),
        ),
    ]
