# Generated by Django 3.1.2 on 2021-01-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechbot', '0014_discorduser_can_dm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
